### ISSUE TITLE
write a blog post to introduce how cool pixelate is

### ISSUE THREAD

**Issue by hoatle** [teracyhq/blog#60]
https://github.com/teracyhq/pixelate

**Comment by codertran** [comment]
JavaScript is a powerful programming language that is used on the front end of most of the websites you access every single day. It makes a website interactive and adds functionality, creating a much more satisfying user experience. We can see more app as carousel slider, slideshow, effect smooth for website, and design game v..v. But now, we have add one app create JavaScript. This is Pixelate app. Of course, it don't only have JavaScript simple but also more and more different library of JavaScript as backbone, underscore...in the code. But don't worry. I can speak about it. Pixelate really, really good, essential, convenient,  for web developer and designer, and anybody want pixelate your images. This app use very simple. I think, don't have any application simple as Pixelate. You only need upload your image in the application in the web, and select area you want then press enter. Conclusion, you only need  click on download button under image, immediate you will to have one image pixelated. Amazing! Perfect!. I warranty with you. This app is no error, very fast, very simple, and no install. The first person use this application, it me!. So now, do you want to try? Upload image and receive pixelated image. Very easy.

**Comment by hoatle** [comment]
title: How to use pixelate javascript library
purpose: to introduce how cool pixelate is

**Comment by hoatle** [comment]
closed, no one handles this (was intended for a test task to a trainee)
